package org.tsxuehu.pm.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tsxuehu.pm.dao.dbobject.MachineDO;
import org.tsxuehu.pm.dao.dbobject.MachineDOExample;

public interface MachineDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int countByExample(MachineDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int deleteByExample(MachineDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int insert(MachineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int insertSelective(MachineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    List<MachineDO> selectByExample(MachineDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    MachineDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MachineDO record, @Param("example") MachineDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MachineDO record, @Param("example") MachineDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MachineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MachineDO record);
}