package org.tsxuehu.pm.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tsxuehu.pm.dao.dbobject.ProjectDO;
import org.tsxuehu.pm.dao.dbobject.ProjectDOExample;

public interface ProjectDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int countByExample(ProjectDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int insert(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    List<ProjectDO> selectByExample(ProjectDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    ProjectDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProjectDO record, @Param("example") ProjectDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProjectDO record, @Param("example") ProjectDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDO record);
}