package org.tsxuehu.pm.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tsxuehu.pm.dao.dbobject.SCMDO;
import org.tsxuehu.pm.dao.dbobject.SCMDOExample;

public interface SCMDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int countByExample(SCMDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int deleteByExample(SCMDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int insert(SCMDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int insertSelective(SCMDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    List<SCMDO> selectByExample(SCMDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    SCMDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SCMDO record, @Param("example") SCMDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SCMDO record, @Param("example") SCMDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SCMDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SCMDO record);
}