package org.tsxuehu.pm.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.tsxuehu.pm.dao.dbobject.ShellDO;
import org.tsxuehu.pm.dao.dbobject.ShellDOExample;

public interface ShellDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int countByExample(ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int deleteByExample(ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int insert(ShellDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int insertSelective(ShellDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    List<ShellDO> selectByExampleWithBLOBs(ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    List<ShellDO> selectByExample(ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    ShellDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShellDO record, @Param("example") ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ShellDO record, @Param("example") ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShellDO record, @Param("example") ShellDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShellDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ShellDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shell
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShellDO record);
}