package org.tsxuehu.pm.dao.dbobject;

import java.util.ArrayList;
import java.util.List;

public class ApplicationDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public ApplicationDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andScmIdIsNull() {
            addCriterion("scm_id is null");
            return (Criteria) this;
        }

        public Criteria andScmIdIsNotNull() {
            addCriterion("scm_id is not null");
            return (Criteria) this;
        }

        public Criteria andScmIdEqualTo(Long value) {
            addCriterion("scm_id =", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdNotEqualTo(Long value) {
            addCriterion("scm_id <>", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdGreaterThan(Long value) {
            addCriterion("scm_id >", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("scm_id >=", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdLessThan(Long value) {
            addCriterion("scm_id <", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdLessThanOrEqualTo(Long value) {
            addCriterion("scm_id <=", value, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdIn(List<Long> values) {
            addCriterion("scm_id in", values, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdNotIn(List<Long> values) {
            addCriterion("scm_id not in", values, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdBetween(Long value1, Long value2) {
            addCriterion("scm_id between", value1, value2, "scmId");
            return (Criteria) this;
        }

        public Criteria andScmIdNotBetween(Long value1, Long value2) {
            addCriterion("scm_id not between", value1, value2, "scmId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdIsNull() {
            addCriterion("gitlab_project_id is null");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdIsNotNull() {
            addCriterion("gitlab_project_id is not null");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdEqualTo(String value) {
            addCriterion("gitlab_project_id =", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdNotEqualTo(String value) {
            addCriterion("gitlab_project_id <>", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdGreaterThan(String value) {
            addCriterion("gitlab_project_id >", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("gitlab_project_id >=", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdLessThan(String value) {
            addCriterion("gitlab_project_id <", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdLessThanOrEqualTo(String value) {
            addCriterion("gitlab_project_id <=", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdLike(String value) {
            addCriterion("gitlab_project_id like", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdNotLike(String value) {
            addCriterion("gitlab_project_id not like", value, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdIn(List<String> values) {
            addCriterion("gitlab_project_id in", values, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdNotIn(List<String> values) {
            addCriterion("gitlab_project_id not in", values, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdBetween(String value1, String value2) {
            addCriterion("gitlab_project_id between", value1, value2, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andGitlabProjectIdNotBetween(String value1, String value2) {
            addCriterion("gitlab_project_id not between", value1, value2, "gitlabProjectId");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesIsNull() {
            addCriterion("daily_machines is null");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesIsNotNull() {
            addCriterion("daily_machines is not null");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesEqualTo(String value) {
            addCriterion("daily_machines =", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesNotEqualTo(String value) {
            addCriterion("daily_machines <>", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesGreaterThan(String value) {
            addCriterion("daily_machines >", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesGreaterThanOrEqualTo(String value) {
            addCriterion("daily_machines >=", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesLessThan(String value) {
            addCriterion("daily_machines <", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesLessThanOrEqualTo(String value) {
            addCriterion("daily_machines <=", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesLike(String value) {
            addCriterion("daily_machines like", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesNotLike(String value) {
            addCriterion("daily_machines not like", value, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesIn(List<String> values) {
            addCriterion("daily_machines in", values, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesNotIn(List<String> values) {
            addCriterion("daily_machines not in", values, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesBetween(String value1, String value2) {
            addCriterion("daily_machines between", value1, value2, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andDailyMachinesNotBetween(String value1, String value2) {
            addCriterion("daily_machines not between", value1, value2, "dailyMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesIsNull() {
            addCriterion("pre_machines is null");
            return (Criteria) this;
        }

        public Criteria andPreMachinesIsNotNull() {
            addCriterion("pre_machines is not null");
            return (Criteria) this;
        }

        public Criteria andPreMachinesEqualTo(String value) {
            addCriterion("pre_machines =", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesNotEqualTo(String value) {
            addCriterion("pre_machines <>", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesGreaterThan(String value) {
            addCriterion("pre_machines >", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesGreaterThanOrEqualTo(String value) {
            addCriterion("pre_machines >=", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesLessThan(String value) {
            addCriterion("pre_machines <", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesLessThanOrEqualTo(String value) {
            addCriterion("pre_machines <=", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesLike(String value) {
            addCriterion("pre_machines like", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesNotLike(String value) {
            addCriterion("pre_machines not like", value, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesIn(List<String> values) {
            addCriterion("pre_machines in", values, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesNotIn(List<String> values) {
            addCriterion("pre_machines not in", values, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesBetween(String value1, String value2) {
            addCriterion("pre_machines between", value1, value2, "preMachines");
            return (Criteria) this;
        }

        public Criteria andPreMachinesNotBetween(String value1, String value2) {
            addCriterion("pre_machines not between", value1, value2, "preMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesIsNull() {
            addCriterion("formal_machines is null");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesIsNotNull() {
            addCriterion("formal_machines is not null");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesEqualTo(String value) {
            addCriterion("formal_machines =", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesNotEqualTo(String value) {
            addCriterion("formal_machines <>", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesGreaterThan(String value) {
            addCriterion("formal_machines >", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesGreaterThanOrEqualTo(String value) {
            addCriterion("formal_machines >=", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesLessThan(String value) {
            addCriterion("formal_machines <", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesLessThanOrEqualTo(String value) {
            addCriterion("formal_machines <=", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesLike(String value) {
            addCriterion("formal_machines like", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesNotLike(String value) {
            addCriterion("formal_machines not like", value, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesIn(List<String> values) {
            addCriterion("formal_machines in", values, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesNotIn(List<String> values) {
            addCriterion("formal_machines not in", values, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesBetween(String value1, String value2) {
            addCriterion("formal_machines between", value1, value2, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andFormalMachinesNotBetween(String value1, String value2) {
            addCriterion("formal_machines not between", value1, value2, "formalMachines");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andPublishersIsNull() {
            addCriterion("publishers is null");
            return (Criteria) this;
        }

        public Criteria andPublishersIsNotNull() {
            addCriterion("publishers is not null");
            return (Criteria) this;
        }

        public Criteria andPublishersEqualTo(String value) {
            addCriterion("publishers =", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersNotEqualTo(String value) {
            addCriterion("publishers <>", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersGreaterThan(String value) {
            addCriterion("publishers >", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersGreaterThanOrEqualTo(String value) {
            addCriterion("publishers >=", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersLessThan(String value) {
            addCriterion("publishers <", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersLessThanOrEqualTo(String value) {
            addCriterion("publishers <=", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersLike(String value) {
            addCriterion("publishers like", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersNotLike(String value) {
            addCriterion("publishers not like", value, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersIn(List<String> values) {
            addCriterion("publishers in", values, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersNotIn(List<String> values) {
            addCriterion("publishers not in", values, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersBetween(String value1, String value2) {
            addCriterion("publishers between", value1, value2, "publishers");
            return (Criteria) this;
        }

        public Criteria andPublishersNotBetween(String value1, String value2) {
            addCriterion("publishers not between", value1, value2, "publishers");
            return (Criteria) this;
        }

        public Criteria andMergeshellidIsNull() {
            addCriterion("mergeShellId is null");
            return (Criteria) this;
        }

        public Criteria andMergeshellidIsNotNull() {
            addCriterion("mergeShellId is not null");
            return (Criteria) this;
        }

        public Criteria andMergeshellidEqualTo(Long value) {
            addCriterion("mergeShellId =", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidNotEqualTo(Long value) {
            addCriterion("mergeShellId <>", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidGreaterThan(Long value) {
            addCriterion("mergeShellId >", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidGreaterThanOrEqualTo(Long value) {
            addCriterion("mergeShellId >=", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidLessThan(Long value) {
            addCriterion("mergeShellId <", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidLessThanOrEqualTo(Long value) {
            addCriterion("mergeShellId <=", value, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidIn(List<Long> values) {
            addCriterion("mergeShellId in", values, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidNotIn(List<Long> values) {
            addCriterion("mergeShellId not in", values, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidBetween(Long value1, Long value2) {
            addCriterion("mergeShellId between", value1, value2, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andMergeshellidNotBetween(Long value1, Long value2) {
            addCriterion("mergeShellId not between", value1, value2, "mergeshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidIsNull() {
            addCriterion("buildShellId is null");
            return (Criteria) this;
        }

        public Criteria andBuildshellidIsNotNull() {
            addCriterion("buildShellId is not null");
            return (Criteria) this;
        }

        public Criteria andBuildshellidEqualTo(Long value) {
            addCriterion("buildShellId =", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidNotEqualTo(Long value) {
            addCriterion("buildShellId <>", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidGreaterThan(Long value) {
            addCriterion("buildShellId >", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidGreaterThanOrEqualTo(Long value) {
            addCriterion("buildShellId >=", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidLessThan(Long value) {
            addCriterion("buildShellId <", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidLessThanOrEqualTo(Long value) {
            addCriterion("buildShellId <=", value, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidIn(List<Long> values) {
            addCriterion("buildShellId in", values, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidNotIn(List<Long> values) {
            addCriterion("buildShellId not in", values, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidBetween(Long value1, Long value2) {
            addCriterion("buildShellId between", value1, value2, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andBuildshellidNotBetween(Long value1, Long value2) {
            addCriterion("buildShellId not between", value1, value2, "buildshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidIsNull() {
            addCriterion("publishShellId is null");
            return (Criteria) this;
        }

        public Criteria andPublishshellidIsNotNull() {
            addCriterion("publishShellId is not null");
            return (Criteria) this;
        }

        public Criteria andPublishshellidEqualTo(Long value) {
            addCriterion("publishShellId =", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidNotEqualTo(Long value) {
            addCriterion("publishShellId <>", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidGreaterThan(Long value) {
            addCriterion("publishShellId >", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidGreaterThanOrEqualTo(Long value) {
            addCriterion("publishShellId >=", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidLessThan(Long value) {
            addCriterion("publishShellId <", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidLessThanOrEqualTo(Long value) {
            addCriterion("publishShellId <=", value, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidIn(List<Long> values) {
            addCriterion("publishShellId in", values, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidNotIn(List<Long> values) {
            addCriterion("publishShellId not in", values, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidBetween(Long value1, Long value2) {
            addCriterion("publishShellId between", value1, value2, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andPublishshellidNotBetween(Long value1, Long value2) {
            addCriterion("publishShellId not between", value1, value2, "publishshellid");
            return (Criteria) this;
        }

        public Criteria andReviewIsNull() {
            addCriterion("review is null");
            return (Criteria) this;
        }

        public Criteria andReviewIsNotNull() {
            addCriterion("review is not null");
            return (Criteria) this;
        }

        public Criteria andReviewEqualTo(String value) {
            addCriterion("review =", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewNotEqualTo(String value) {
            addCriterion("review <>", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewGreaterThan(String value) {
            addCriterion("review >", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewGreaterThanOrEqualTo(String value) {
            addCriterion("review >=", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewLessThan(String value) {
            addCriterion("review <", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewLessThanOrEqualTo(String value) {
            addCriterion("review <=", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewLike(String value) {
            addCriterion("review like", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewNotLike(String value) {
            addCriterion("review not like", value, "review");
            return (Criteria) this;
        }

        public Criteria andReviewIn(List<String> values) {
            addCriterion("review in", values, "review");
            return (Criteria) this;
        }

        public Criteria andReviewNotIn(List<String> values) {
            addCriterion("review not in", values, "review");
            return (Criteria) this;
        }

        public Criteria andReviewBetween(String value1, String value2) {
            addCriterion("review between", value1, value2, "review");
            return (Criteria) this;
        }

        public Criteria andReviewNotBetween(String value1, String value2) {
            addCriterion("review not between", value1, value2, "review");
            return (Criteria) this;
        }

        public Criteria andAppParamIsNull() {
            addCriterion("app_param is null");
            return (Criteria) this;
        }

        public Criteria andAppParamIsNotNull() {
            addCriterion("app_param is not null");
            return (Criteria) this;
        }

        public Criteria andAppParamEqualTo(String value) {
            addCriterion("app_param =", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamNotEqualTo(String value) {
            addCriterion("app_param <>", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamGreaterThan(String value) {
            addCriterion("app_param >", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamGreaterThanOrEqualTo(String value) {
            addCriterion("app_param >=", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamLessThan(String value) {
            addCriterion("app_param <", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamLessThanOrEqualTo(String value) {
            addCriterion("app_param <=", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamLike(String value) {
            addCriterion("app_param like", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamNotLike(String value) {
            addCriterion("app_param not like", value, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamIn(List<String> values) {
            addCriterion("app_param in", values, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamNotIn(List<String> values) {
            addCriterion("app_param not in", values, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamBetween(String value1, String value2) {
            addCriterion("app_param between", value1, value2, "appParam");
            return (Criteria) this;
        }

        public Criteria andAppParamNotBetween(String value1, String value2) {
            addCriterion("app_param not between", value1, value2, "appParam");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table application
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}