package org.tsxuehu.pm.dao.dbobject;

public class ApplicationDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.scm_id
     *
     * @mbggenerated
     */
    private Long scmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.gitlab_project_id
     *
     * @mbggenerated
     */
    private String gitlabProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.daily_machines
     *
     * @mbggenerated
     */
    private String dailyMachines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.pre_machines
     *
     * @mbggenerated
     */
    private String preMachines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.formal_machines
     *
     * @mbggenerated
     */
    private String formalMachines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.owner
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.publishers
     *
     * @mbggenerated
     */
    private String publishers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.mergeShellId
     *
     * @mbggenerated
     */
    private Long mergeshellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.buildShellId
     *
     * @mbggenerated
     */
    private Long buildshellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.publishShellId
     *
     * @mbggenerated
     */
    private Long publishshellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.review
     *
     * @mbggenerated
     */
    private String review;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_param
     *
     * @mbggenerated
     */
    private String appParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.id
     *
     * @return the value of application.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.id
     *
     * @param id the value for application.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.name
     *
     * @return the value of application.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.name
     *
     * @param name the value for application.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.description
     *
     * @return the value of application.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.description
     *
     * @param description the value for application.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.scm_id
     *
     * @return the value of application.scm_id
     *
     * @mbggenerated
     */
    public Long getScmId() {
        return scmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.scm_id
     *
     * @param scmId the value for application.scm_id
     *
     * @mbggenerated
     */
    public void setScmId(Long scmId) {
        this.scmId = scmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.gitlab_project_id
     *
     * @return the value of application.gitlab_project_id
     *
     * @mbggenerated
     */
    public String getGitlabProjectId() {
        return gitlabProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.gitlab_project_id
     *
     * @param gitlabProjectId the value for application.gitlab_project_id
     *
     * @mbggenerated
     */
    public void setGitlabProjectId(String gitlabProjectId) {
        this.gitlabProjectId = gitlabProjectId == null ? null : gitlabProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.daily_machines
     *
     * @return the value of application.daily_machines
     *
     * @mbggenerated
     */
    public String getDailyMachines() {
        return dailyMachines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.daily_machines
     *
     * @param dailyMachines the value for application.daily_machines
     *
     * @mbggenerated
     */
    public void setDailyMachines(String dailyMachines) {
        this.dailyMachines = dailyMachines == null ? null : dailyMachines.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.pre_machines
     *
     * @return the value of application.pre_machines
     *
     * @mbggenerated
     */
    public String getPreMachines() {
        return preMachines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.pre_machines
     *
     * @param preMachines the value for application.pre_machines
     *
     * @mbggenerated
     */
    public void setPreMachines(String preMachines) {
        this.preMachines = preMachines == null ? null : preMachines.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.formal_machines
     *
     * @return the value of application.formal_machines
     *
     * @mbggenerated
     */
    public String getFormalMachines() {
        return formalMachines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.formal_machines
     *
     * @param formalMachines the value for application.formal_machines
     *
     * @mbggenerated
     */
    public void setFormalMachines(String formalMachines) {
        this.formalMachines = formalMachines == null ? null : formalMachines.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.owner
     *
     * @return the value of application.owner
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.owner
     *
     * @param owner the value for application.owner
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.publishers
     *
     * @return the value of application.publishers
     *
     * @mbggenerated
     */
    public String getPublishers() {
        return publishers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.publishers
     *
     * @param publishers the value for application.publishers
     *
     * @mbggenerated
     */
    public void setPublishers(String publishers) {
        this.publishers = publishers == null ? null : publishers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.mergeShellId
     *
     * @return the value of application.mergeShellId
     *
     * @mbggenerated
     */
    public Long getMergeshellid() {
        return mergeshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.mergeShellId
     *
     * @param mergeshellid the value for application.mergeShellId
     *
     * @mbggenerated
     */
    public void setMergeshellid(Long mergeshellid) {
        this.mergeshellid = mergeshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.buildShellId
     *
     * @return the value of application.buildShellId
     *
     * @mbggenerated
     */
    public Long getBuildshellid() {
        return buildshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.buildShellId
     *
     * @param buildshellid the value for application.buildShellId
     *
     * @mbggenerated
     */
    public void setBuildshellid(Long buildshellid) {
        this.buildshellid = buildshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.publishShellId
     *
     * @return the value of application.publishShellId
     *
     * @mbggenerated
     */
    public Long getPublishshellid() {
        return publishshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.publishShellId
     *
     * @param publishshellid the value for application.publishShellId
     *
     * @mbggenerated
     */
    public void setPublishshellid(Long publishshellid) {
        this.publishshellid = publishshellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.review
     *
     * @return the value of application.review
     *
     * @mbggenerated
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.review
     *
     * @param review the value for application.review
     *
     * @mbggenerated
     */
    public void setReview(String review) {
        this.review = review == null ? null : review.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_param
     *
     * @return the value of application.app_param
     *
     * @mbggenerated
     */
    public String getAppParam() {
        return appParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_param
     *
     * @param appParam the value for application.app_param
     *
     * @mbggenerated
     */
    public void setAppParam(String appParam) {
        this.appParam = appParam == null ? null : appParam.trim();
    }
}