package org.tsxuehu.pm.dao.dbobject;

import java.util.ArrayList;
import java.util.List;

public class BranchDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public BranchDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andScmbranchidIsNull() {
            addCriterion("scmBranchId is null");
            return (Criteria) this;
        }

        public Criteria andScmbranchidIsNotNull() {
            addCriterion("scmBranchId is not null");
            return (Criteria) this;
        }

        public Criteria andScmbranchidEqualTo(String value) {
            addCriterion("scmBranchId =", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidNotEqualTo(String value) {
            addCriterion("scmBranchId <>", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidGreaterThan(String value) {
            addCriterion("scmBranchId >", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidGreaterThanOrEqualTo(String value) {
            addCriterion("scmBranchId >=", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidLessThan(String value) {
            addCriterion("scmBranchId <", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidLessThanOrEqualTo(String value) {
            addCriterion("scmBranchId <=", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidLike(String value) {
            addCriterion("scmBranchId like", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidNotLike(String value) {
            addCriterion("scmBranchId not like", value, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidIn(List<String> values) {
            addCriterion("scmBranchId in", values, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidNotIn(List<String> values) {
            addCriterion("scmBranchId not in", values, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidBetween(String value1, String value2) {
            addCriterion("scmBranchId between", value1, value2, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andScmbranchidNotBetween(String value1, String value2) {
            addCriterion("scmBranchId not between", value1, value2, "scmbranchid");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIsNull() {
            addCriterion("repositoryLocation is null");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIsNotNull() {
            addCriterion("repositoryLocation is not null");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationEqualTo(String value) {
            addCriterion("repositoryLocation =", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotEqualTo(String value) {
            addCriterion("repositoryLocation <>", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationGreaterThan(String value) {
            addCriterion("repositoryLocation >", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationGreaterThanOrEqualTo(String value) {
            addCriterion("repositoryLocation >=", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLessThan(String value) {
            addCriterion("repositoryLocation <", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLessThanOrEqualTo(String value) {
            addCriterion("repositoryLocation <=", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLike(String value) {
            addCriterion("repositoryLocation like", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotLike(String value) {
            addCriterion("repositoryLocation not like", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIn(List<String> values) {
            addCriterion("repositoryLocation in", values, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotIn(List<String> values) {
            addCriterion("repositoryLocation not in", values, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationBetween(String value1, String value2) {
            addCriterion("repositoryLocation between", value1, value2, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotBetween(String value1, String value2) {
            addCriterion("repositoryLocation not between", value1, value2, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andApplicationidIsNull() {
            addCriterion("applicationId is null");
            return (Criteria) this;
        }

        public Criteria andApplicationidIsNotNull() {
            addCriterion("applicationId is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationidEqualTo(Long value) {
            addCriterion("applicationId =", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotEqualTo(Long value) {
            addCriterion("applicationId <>", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidGreaterThan(Long value) {
            addCriterion("applicationId >", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidGreaterThanOrEqualTo(Long value) {
            addCriterion("applicationId >=", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidLessThan(Long value) {
            addCriterion("applicationId <", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidLessThanOrEqualTo(Long value) {
            addCriterion("applicationId <=", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidIn(List<Long> values) {
            addCriterion("applicationId in", values, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotIn(List<Long> values) {
            addCriterion("applicationId not in", values, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidBetween(Long value1, Long value2) {
            addCriterion("applicationId between", value1, value2, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotBetween(Long value1, Long value2) {
            addCriterion("applicationId not between", value1, value2, "applicationid");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNull() {
            addCriterion("projectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNotNull() {
            addCriterion("projectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectidEqualTo(Long value) {
            addCriterion("projectId =", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotEqualTo(Long value) {
            addCriterion("projectId <>", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThan(Long value) {
            addCriterion("projectId >", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThanOrEqualTo(Long value) {
            addCriterion("projectId >=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThan(Long value) {
            addCriterion("projectId <", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThanOrEqualTo(Long value) {
            addCriterion("projectId <=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidIn(List<Long> values) {
            addCriterion("projectId in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotIn(List<Long> values) {
            addCriterion("projectId not in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidBetween(Long value1, Long value2) {
            addCriterion("projectId between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotBetween(Long value1, Long value2) {
            addCriterion("projectId not between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andExtraIsNull() {
            addCriterion("extra is null");
            return (Criteria) this;
        }

        public Criteria andExtraIsNotNull() {
            addCriterion("extra is not null");
            return (Criteria) this;
        }

        public Criteria andExtraEqualTo(String value) {
            addCriterion("extra =", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotEqualTo(String value) {
            addCriterion("extra <>", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThan(String value) {
            addCriterion("extra >", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThanOrEqualTo(String value) {
            addCriterion("extra >=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThan(String value) {
            addCriterion("extra <", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThanOrEqualTo(String value) {
            addCriterion("extra <=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLike(String value) {
            addCriterion("extra like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotLike(String value) {
            addCriterion("extra not like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraIn(List<String> values) {
            addCriterion("extra in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotIn(List<String> values) {
            addCriterion("extra not in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraBetween(String value1, String value2) {
            addCriterion("extra between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotBetween(String value1, String value2) {
            addCriterion("extra not between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andDeployserverIsNull() {
            addCriterion("deployServer is null");
            return (Criteria) this;
        }

        public Criteria andDeployserverIsNotNull() {
            addCriterion("deployServer is not null");
            return (Criteria) this;
        }

        public Criteria andDeployserverEqualTo(String value) {
            addCriterion("deployServer =", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverNotEqualTo(String value) {
            addCriterion("deployServer <>", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverGreaterThan(String value) {
            addCriterion("deployServer >", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverGreaterThanOrEqualTo(String value) {
            addCriterion("deployServer >=", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverLessThan(String value) {
            addCriterion("deployServer <", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverLessThanOrEqualTo(String value) {
            addCriterion("deployServer <=", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverLike(String value) {
            addCriterion("deployServer like", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverNotLike(String value) {
            addCriterion("deployServer not like", value, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverIn(List<String> values) {
            addCriterion("deployServer in", values, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverNotIn(List<String> values) {
            addCriterion("deployServer not in", values, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverBetween(String value1, String value2) {
            addCriterion("deployServer between", value1, value2, "deployserver");
            return (Criteria) this;
        }

        public Criteria andDeployserverNotBetween(String value1, String value2) {
            addCriterion("deployServer not between", value1, value2, "deployserver");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointIsNull() {
            addCriterion("checkoutPoint is null");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointIsNotNull() {
            addCriterion("checkoutPoint is not null");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointEqualTo(String value) {
            addCriterion("checkoutPoint =", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointNotEqualTo(String value) {
            addCriterion("checkoutPoint <>", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointGreaterThan(String value) {
            addCriterion("checkoutPoint >", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointGreaterThanOrEqualTo(String value) {
            addCriterion("checkoutPoint >=", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointLessThan(String value) {
            addCriterion("checkoutPoint <", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointLessThanOrEqualTo(String value) {
            addCriterion("checkoutPoint <=", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointLike(String value) {
            addCriterion("checkoutPoint like", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointNotLike(String value) {
            addCriterion("checkoutPoint not like", value, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointIn(List<String> values) {
            addCriterion("checkoutPoint in", values, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointNotIn(List<String> values) {
            addCriterion("checkoutPoint not in", values, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointBetween(String value1, String value2) {
            addCriterion("checkoutPoint between", value1, value2, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCheckoutpointNotBetween(String value1, String value2) {
            addCriterion("checkoutPoint not between", value1, value2, "checkoutpoint");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table branch
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}