package org.tsxuehu.pm.dao.dbobject;

public class GroupBranchRelationDO extends GroupBranchRelationDOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_branch_relation.build_tag
     *
     * @mbggenerated
     */
    private String buildTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_branch_relation.build_tag
     *
     * @return the value of group_branch_relation.build_tag
     *
     * @mbggenerated
     */
    public String getBuildTag() {
        return buildTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_branch_relation.build_tag
     *
     * @param buildTag the value for group_branch_relation.build_tag
     *
     * @mbggenerated
     */
    public void setBuildTag(String buildTag) {
        this.buildTag = buildTag == null ? null : buildTag.trim();
    }
}