package org.tsxuehu.pm.dao.dbobject;

public class GroupDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.servers
     *
     * @mbggenerated
     */
    private String servers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.integrationBranch
     *
     * @mbggenerated
     */
    private String integrationbranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.projectId
     *
     * @mbggenerated
     */
    private Long projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.branchId
     *
     * @mbggenerated
     */
    private Long branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.applicationId
     *
     * @mbggenerated
     */
    private Long applicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.configuration
     *
     * @mbggenerated
     */
    private String configuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.buildPhrase
     *
     * @mbggenerated
     */
    private String buildphrase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.buidRate
     *
     * @mbggenerated
     */
    private Integer buidrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.pushPhrase
     *
     * @mbggenerated
     */
    private String pushphrase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.pushRate
     *
     * @mbggenerated
     */
    private Integer pushrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.repositoryLocation
     *
     * @mbggenerated
     */
    private String repositorylocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.description
     *
     * @return the value of group.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.description
     *
     * @param description the value for group.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.servers
     *
     * @return the value of group.servers
     *
     * @mbggenerated
     */
    public String getServers() {
        return servers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.servers
     *
     * @param servers the value for group.servers
     *
     * @mbggenerated
     */
    public void setServers(String servers) {
        this.servers = servers == null ? null : servers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.integrationBranch
     *
     * @return the value of group.integrationBranch
     *
     * @mbggenerated
     */
    public String getIntegrationbranch() {
        return integrationbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.integrationBranch
     *
     * @param integrationbranch the value for group.integrationBranch
     *
     * @mbggenerated
     */
    public void setIntegrationbranch(String integrationbranch) {
        this.integrationbranch = integrationbranch == null ? null : integrationbranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.projectId
     *
     * @return the value of group.projectId
     *
     * @mbggenerated
     */
    public Long getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.projectId
     *
     * @param projectid the value for group.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Long projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.branchId
     *
     * @return the value of group.branchId
     *
     * @mbggenerated
     */
    public Long getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.branchId
     *
     * @param branchid the value for group.branchId
     *
     * @mbggenerated
     */
    public void setBranchid(Long branchid) {
        this.branchid = branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.applicationId
     *
     * @return the value of group.applicationId
     *
     * @mbggenerated
     */
    public Long getApplicationid() {
        return applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.applicationId
     *
     * @param applicationid the value for group.applicationId
     *
     * @mbggenerated
     */
    public void setApplicationid(Long applicationid) {
        this.applicationid = applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.configuration
     *
     * @return the value of group.configuration
     *
     * @mbggenerated
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.configuration
     *
     * @param configuration the value for group.configuration
     *
     * @mbggenerated
     */
    public void setConfiguration(String configuration) {
        this.configuration = configuration == null ? null : configuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.type
     *
     * @return the value of group.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.type
     *
     * @param type the value for group.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.buildPhrase
     *
     * @return the value of group.buildPhrase
     *
     * @mbggenerated
     */
    public String getBuildphrase() {
        return buildphrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.buildPhrase
     *
     * @param buildphrase the value for group.buildPhrase
     *
     * @mbggenerated
     */
    public void setBuildphrase(String buildphrase) {
        this.buildphrase = buildphrase == null ? null : buildphrase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.buidRate
     *
     * @return the value of group.buidRate
     *
     * @mbggenerated
     */
    public Integer getBuidrate() {
        return buidrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.buidRate
     *
     * @param buidrate the value for group.buidRate
     *
     * @mbggenerated
     */
    public void setBuidrate(Integer buidrate) {
        this.buidrate = buidrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.pushPhrase
     *
     * @return the value of group.pushPhrase
     *
     * @mbggenerated
     */
    public String getPushphrase() {
        return pushphrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.pushPhrase
     *
     * @param pushphrase the value for group.pushPhrase
     *
     * @mbggenerated
     */
    public void setPushphrase(String pushphrase) {
        this.pushphrase = pushphrase == null ? null : pushphrase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.pushRate
     *
     * @return the value of group.pushRate
     *
     * @mbggenerated
     */
    public Integer getPushrate() {
        return pushrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.pushRate
     *
     * @param pushrate the value for group.pushRate
     *
     * @mbggenerated
     */
    public void setPushrate(Integer pushrate) {
        this.pushrate = pushrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.repositoryLocation
     *
     * @return the value of group.repositoryLocation
     *
     * @mbggenerated
     */
    public String getRepositorylocation() {
        return repositorylocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.repositoryLocation
     *
     * @param repositorylocation the value for group.repositoryLocation
     *
     * @mbggenerated
     */
    public void setRepositorylocation(String repositorylocation) {
        this.repositorylocation = repositorylocation == null ? null : repositorylocation.trim();
    }
}