package org.tsxuehu.pm.dao.dbobject;

import java.util.ArrayList;
import java.util.List;

public class GroupDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public GroupDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andServersIsNull() {
            addCriterion("servers is null");
            return (Criteria) this;
        }

        public Criteria andServersIsNotNull() {
            addCriterion("servers is not null");
            return (Criteria) this;
        }

        public Criteria andServersEqualTo(String value) {
            addCriterion("servers =", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersNotEqualTo(String value) {
            addCriterion("servers <>", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersGreaterThan(String value) {
            addCriterion("servers >", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersGreaterThanOrEqualTo(String value) {
            addCriterion("servers >=", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersLessThan(String value) {
            addCriterion("servers <", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersLessThanOrEqualTo(String value) {
            addCriterion("servers <=", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersLike(String value) {
            addCriterion("servers like", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersNotLike(String value) {
            addCriterion("servers not like", value, "servers");
            return (Criteria) this;
        }

        public Criteria andServersIn(List<String> values) {
            addCriterion("servers in", values, "servers");
            return (Criteria) this;
        }

        public Criteria andServersNotIn(List<String> values) {
            addCriterion("servers not in", values, "servers");
            return (Criteria) this;
        }

        public Criteria andServersBetween(String value1, String value2) {
            addCriterion("servers between", value1, value2, "servers");
            return (Criteria) this;
        }

        public Criteria andServersNotBetween(String value1, String value2) {
            addCriterion("servers not between", value1, value2, "servers");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchIsNull() {
            addCriterion("integrationBranch is null");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchIsNotNull() {
            addCriterion("integrationBranch is not null");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchEqualTo(String value) {
            addCriterion("integrationBranch =", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchNotEqualTo(String value) {
            addCriterion("integrationBranch <>", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchGreaterThan(String value) {
            addCriterion("integrationBranch >", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchGreaterThanOrEqualTo(String value) {
            addCriterion("integrationBranch >=", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchLessThan(String value) {
            addCriterion("integrationBranch <", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchLessThanOrEqualTo(String value) {
            addCriterion("integrationBranch <=", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchLike(String value) {
            addCriterion("integrationBranch like", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchNotLike(String value) {
            addCriterion("integrationBranch not like", value, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchIn(List<String> values) {
            addCriterion("integrationBranch in", values, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchNotIn(List<String> values) {
            addCriterion("integrationBranch not in", values, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchBetween(String value1, String value2) {
            addCriterion("integrationBranch between", value1, value2, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andIntegrationbranchNotBetween(String value1, String value2) {
            addCriterion("integrationBranch not between", value1, value2, "integrationbranch");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNull() {
            addCriterion("projectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNotNull() {
            addCriterion("projectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectidEqualTo(Long value) {
            addCriterion("projectId =", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotEqualTo(Long value) {
            addCriterion("projectId <>", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThan(Long value) {
            addCriterion("projectId >", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThanOrEqualTo(Long value) {
            addCriterion("projectId >=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThan(Long value) {
            addCriterion("projectId <", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThanOrEqualTo(Long value) {
            addCriterion("projectId <=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidIn(List<Long> values) {
            addCriterion("projectId in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotIn(List<Long> values) {
            addCriterion("projectId not in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidBetween(Long value1, Long value2) {
            addCriterion("projectId between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotBetween(Long value1, Long value2) {
            addCriterion("projectId not between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andBranchidIsNull() {
            addCriterion("branchId is null");
            return (Criteria) this;
        }

        public Criteria andBranchidIsNotNull() {
            addCriterion("branchId is not null");
            return (Criteria) this;
        }

        public Criteria andBranchidEqualTo(Long value) {
            addCriterion("branchId =", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotEqualTo(Long value) {
            addCriterion("branchId <>", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidGreaterThan(Long value) {
            addCriterion("branchId >", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidGreaterThanOrEqualTo(Long value) {
            addCriterion("branchId >=", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidLessThan(Long value) {
            addCriterion("branchId <", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidLessThanOrEqualTo(Long value) {
            addCriterion("branchId <=", value, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidIn(List<Long> values) {
            addCriterion("branchId in", values, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotIn(List<Long> values) {
            addCriterion("branchId not in", values, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidBetween(Long value1, Long value2) {
            addCriterion("branchId between", value1, value2, "branchid");
            return (Criteria) this;
        }

        public Criteria andBranchidNotBetween(Long value1, Long value2) {
            addCriterion("branchId not between", value1, value2, "branchid");
            return (Criteria) this;
        }

        public Criteria andApplicationidIsNull() {
            addCriterion("applicationId is null");
            return (Criteria) this;
        }

        public Criteria andApplicationidIsNotNull() {
            addCriterion("applicationId is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationidEqualTo(Long value) {
            addCriterion("applicationId =", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotEqualTo(Long value) {
            addCriterion("applicationId <>", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidGreaterThan(Long value) {
            addCriterion("applicationId >", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidGreaterThanOrEqualTo(Long value) {
            addCriterion("applicationId >=", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidLessThan(Long value) {
            addCriterion("applicationId <", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidLessThanOrEqualTo(Long value) {
            addCriterion("applicationId <=", value, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidIn(List<Long> values) {
            addCriterion("applicationId in", values, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotIn(List<Long> values) {
            addCriterion("applicationId not in", values, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidBetween(Long value1, Long value2) {
            addCriterion("applicationId between", value1, value2, "applicationid");
            return (Criteria) this;
        }

        public Criteria andApplicationidNotBetween(Long value1, Long value2) {
            addCriterion("applicationId not between", value1, value2, "applicationid");
            return (Criteria) this;
        }

        public Criteria andConfigurationIsNull() {
            addCriterion("configuration is null");
            return (Criteria) this;
        }

        public Criteria andConfigurationIsNotNull() {
            addCriterion("configuration is not null");
            return (Criteria) this;
        }

        public Criteria andConfigurationEqualTo(String value) {
            addCriterion("configuration =", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationNotEqualTo(String value) {
            addCriterion("configuration <>", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationGreaterThan(String value) {
            addCriterion("configuration >", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationGreaterThanOrEqualTo(String value) {
            addCriterion("configuration >=", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationLessThan(String value) {
            addCriterion("configuration <", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationLessThanOrEqualTo(String value) {
            addCriterion("configuration <=", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationLike(String value) {
            addCriterion("configuration like", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationNotLike(String value) {
            addCriterion("configuration not like", value, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationIn(List<String> values) {
            addCriterion("configuration in", values, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationNotIn(List<String> values) {
            addCriterion("configuration not in", values, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationBetween(String value1, String value2) {
            addCriterion("configuration between", value1, value2, "configuration");
            return (Criteria) this;
        }

        public Criteria andConfigurationNotBetween(String value1, String value2) {
            addCriterion("configuration not between", value1, value2, "configuration");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBuildphraseIsNull() {
            addCriterion("buildPhrase is null");
            return (Criteria) this;
        }

        public Criteria andBuildphraseIsNotNull() {
            addCriterion("buildPhrase is not null");
            return (Criteria) this;
        }

        public Criteria andBuildphraseEqualTo(String value) {
            addCriterion("buildPhrase =", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseNotEqualTo(String value) {
            addCriterion("buildPhrase <>", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseGreaterThan(String value) {
            addCriterion("buildPhrase >", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseGreaterThanOrEqualTo(String value) {
            addCriterion("buildPhrase >=", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseLessThan(String value) {
            addCriterion("buildPhrase <", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseLessThanOrEqualTo(String value) {
            addCriterion("buildPhrase <=", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseLike(String value) {
            addCriterion("buildPhrase like", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseNotLike(String value) {
            addCriterion("buildPhrase not like", value, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseIn(List<String> values) {
            addCriterion("buildPhrase in", values, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseNotIn(List<String> values) {
            addCriterion("buildPhrase not in", values, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseBetween(String value1, String value2) {
            addCriterion("buildPhrase between", value1, value2, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuildphraseNotBetween(String value1, String value2) {
            addCriterion("buildPhrase not between", value1, value2, "buildphrase");
            return (Criteria) this;
        }

        public Criteria andBuidrateIsNull() {
            addCriterion("buidRate is null");
            return (Criteria) this;
        }

        public Criteria andBuidrateIsNotNull() {
            addCriterion("buidRate is not null");
            return (Criteria) this;
        }

        public Criteria andBuidrateEqualTo(Integer value) {
            addCriterion("buidRate =", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateNotEqualTo(Integer value) {
            addCriterion("buidRate <>", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateGreaterThan(Integer value) {
            addCriterion("buidRate >", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateGreaterThanOrEqualTo(Integer value) {
            addCriterion("buidRate >=", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateLessThan(Integer value) {
            addCriterion("buidRate <", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateLessThanOrEqualTo(Integer value) {
            addCriterion("buidRate <=", value, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateIn(List<Integer> values) {
            addCriterion("buidRate in", values, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateNotIn(List<Integer> values) {
            addCriterion("buidRate not in", values, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateBetween(Integer value1, Integer value2) {
            addCriterion("buidRate between", value1, value2, "buidrate");
            return (Criteria) this;
        }

        public Criteria andBuidrateNotBetween(Integer value1, Integer value2) {
            addCriterion("buidRate not between", value1, value2, "buidrate");
            return (Criteria) this;
        }

        public Criteria andPushphraseIsNull() {
            addCriterion("pushPhrase is null");
            return (Criteria) this;
        }

        public Criteria andPushphraseIsNotNull() {
            addCriterion("pushPhrase is not null");
            return (Criteria) this;
        }

        public Criteria andPushphraseEqualTo(String value) {
            addCriterion("pushPhrase =", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseNotEqualTo(String value) {
            addCriterion("pushPhrase <>", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseGreaterThan(String value) {
            addCriterion("pushPhrase >", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseGreaterThanOrEqualTo(String value) {
            addCriterion("pushPhrase >=", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseLessThan(String value) {
            addCriterion("pushPhrase <", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseLessThanOrEqualTo(String value) {
            addCriterion("pushPhrase <=", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseLike(String value) {
            addCriterion("pushPhrase like", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseNotLike(String value) {
            addCriterion("pushPhrase not like", value, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseIn(List<String> values) {
            addCriterion("pushPhrase in", values, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseNotIn(List<String> values) {
            addCriterion("pushPhrase not in", values, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseBetween(String value1, String value2) {
            addCriterion("pushPhrase between", value1, value2, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushphraseNotBetween(String value1, String value2) {
            addCriterion("pushPhrase not between", value1, value2, "pushphrase");
            return (Criteria) this;
        }

        public Criteria andPushrateIsNull() {
            addCriterion("pushRate is null");
            return (Criteria) this;
        }

        public Criteria andPushrateIsNotNull() {
            addCriterion("pushRate is not null");
            return (Criteria) this;
        }

        public Criteria andPushrateEqualTo(Integer value) {
            addCriterion("pushRate =", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateNotEqualTo(Integer value) {
            addCriterion("pushRate <>", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateGreaterThan(Integer value) {
            addCriterion("pushRate >", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateGreaterThanOrEqualTo(Integer value) {
            addCriterion("pushRate >=", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateLessThan(Integer value) {
            addCriterion("pushRate <", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateLessThanOrEqualTo(Integer value) {
            addCriterion("pushRate <=", value, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateIn(List<Integer> values) {
            addCriterion("pushRate in", values, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateNotIn(List<Integer> values) {
            addCriterion("pushRate not in", values, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateBetween(Integer value1, Integer value2) {
            addCriterion("pushRate between", value1, value2, "pushrate");
            return (Criteria) this;
        }

        public Criteria andPushrateNotBetween(Integer value1, Integer value2) {
            addCriterion("pushRate not between", value1, value2, "pushrate");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIsNull() {
            addCriterion("repositoryLocation is null");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIsNotNull() {
            addCriterion("repositoryLocation is not null");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationEqualTo(String value) {
            addCriterion("repositoryLocation =", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotEqualTo(String value) {
            addCriterion("repositoryLocation <>", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationGreaterThan(String value) {
            addCriterion("repositoryLocation >", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationGreaterThanOrEqualTo(String value) {
            addCriterion("repositoryLocation >=", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLessThan(String value) {
            addCriterion("repositoryLocation <", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLessThanOrEqualTo(String value) {
            addCriterion("repositoryLocation <=", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationLike(String value) {
            addCriterion("repositoryLocation like", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotLike(String value) {
            addCriterion("repositoryLocation not like", value, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationIn(List<String> values) {
            addCriterion("repositoryLocation in", values, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotIn(List<String> values) {
            addCriterion("repositoryLocation not in", values, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationBetween(String value1, String value2) {
            addCriterion("repositoryLocation between", value1, value2, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andRepositorylocationNotBetween(String value1, String value2) {
            addCriterion("repositoryLocation not between", value1, value2, "repositorylocation");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationIsNull() {
            addCriterion("needReintegration is null");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationIsNotNull() {
            addCriterion("needReintegration is not null");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationEqualTo(Byte value) {
            addCriterion("needReintegration =", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationNotEqualTo(Byte value) {
            addCriterion("needReintegration <>", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationGreaterThan(Byte value) {
            addCriterion("needReintegration >", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationGreaterThanOrEqualTo(Byte value) {
            addCriterion("needReintegration >=", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationLessThan(Byte value) {
            addCriterion("needReintegration <", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationLessThanOrEqualTo(Byte value) {
            addCriterion("needReintegration <=", value, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationIn(List<Byte> values) {
            addCriterion("needReintegration in", values, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationNotIn(List<Byte> values) {
            addCriterion("needReintegration not in", values, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationBetween(Byte value1, Byte value2) {
            addCriterion("needReintegration between", value1, value2, "needreintegration");
            return (Criteria) this;
        }

        public Criteria andNeedreintegrationNotBetween(Byte value1, Byte value2) {
            addCriterion("needReintegration not between", value1, value2, "needreintegration");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table group
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}