package org.tsxuehu.pm.dao.dbobject;

public class GroupBranchRelationDOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_branch_relation.branchId
     *
     * @mbggenerated
     */
    private Long branchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_branch_relation.groupId
     *
     * @mbggenerated
     */
    private Long groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_branch_relation.branchId
     *
     * @return the value of group_branch_relation.branchId
     *
     * @mbggenerated
     */
    public Long getBranchid() {
        return branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_branch_relation.branchId
     *
     * @param branchid the value for group_branch_relation.branchId
     *
     * @mbggenerated
     */
    public void setBranchid(Long branchid) {
        this.branchid = branchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_branch_relation.groupId
     *
     * @return the value of group_branch_relation.groupId
     *
     * @mbggenerated
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_branch_relation.groupId
     *
     * @param groupid the value for group_branch_relation.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }
}