package org.tsxuehu.pm.dao.dbobject;

public class ProjectDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.developers
     *
     * @mbggenerated
     */
    private String developers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.testers
     *
     * @mbggenerated
     */
    private String testers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.codeReviewer
     *
     * @mbggenerated
     */
    private String codereviewer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.creator
     *
     * @return the value of project.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.creator
     *
     * @param creator the value for project.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.developers
     *
     * @return the value of project.developers
     *
     * @mbggenerated
     */
    public String getDevelopers() {
        return developers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.developers
     *
     * @param developers the value for project.developers
     *
     * @mbggenerated
     */
    public void setDevelopers(String developers) {
        this.developers = developers == null ? null : developers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.testers
     *
     * @return the value of project.testers
     *
     * @mbggenerated
     */
    public String getTesters() {
        return testers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.testers
     *
     * @param testers the value for project.testers
     *
     * @mbggenerated
     */
    public void setTesters(String testers) {
        this.testers = testers == null ? null : testers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.codeReviewer
     *
     * @return the value of project.codeReviewer
     *
     * @mbggenerated
     */
    public String getCodereviewer() {
        return codereviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.codeReviewer
     *
     * @param codereviewer the value for project.codeReviewer
     *
     * @mbggenerated
     */
    public void setCodereviewer(String codereviewer) {
        this.codereviewer = codereviewer == null ? null : codereviewer.trim();
    }
}