package org.tsxuehu.pm.dao.dbobject;

public class SCMDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scm.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scm.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scm.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scm.configure
     *
     * @mbggenerated
     */
    private String configure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm.id
     *
     * @return the value of scm.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm.id
     *
     * @param id the value for scm.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm.name
     *
     * @return the value of scm.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm.name
     *
     * @param name the value for scm.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm.type
     *
     * @return the value of scm.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm.type
     *
     * @param type the value for scm.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scm.configure
     *
     * @return the value of scm.configure
     *
     * @mbggenerated
     */
    public String getConfigure() {
        return configure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scm.configure
     *
     * @param configure the value for scm.configure
     *
     * @mbggenerated
     */
    public void setConfigure(String configure) {
        this.configure = configure == null ? null : configure.trim();
    }
}